Fix workflow.

diff --git a/.github/workflows/test-localnet.yml b/.github/workflows/test-localnet.yml
--- a/.github/workflows/test-localnet.yml
+++ b/.github/workflows/test-localnet.yml
@@ -48,7 +48,12 @@ jobs:
           python3 -m multiversx_sdk_cli.cli localnet config --configfile=./multiversx_sdk_cli/tests/testdata/localnet_with_resolution_remote.toml
           python3 -m multiversx_sdk_cli.cli localnet start --configfile=./multiversx_sdk_cli/tests/testdata/localnet_with_resolution_remote.toml --stop-after-seconds=120
 
-          grep -r --include=\*.log "started processing block - test" ./localnet || exit 1
+          if grep -r --include=\*.log "started processing block" ./localnet; then
+            echo "The localnet processed blocks successfully."
+          else
+            echo "The localnet failed to process blocks."
+            exit 1
+          fi
 
       - name: Smoke test (with resolution == local)
         run: |
@@ -68,4 +73,9 @@ jobs:
           python3 -m multiversx_sdk_cli.cli localnet config --configfile=./multiversx_sdk_cli/tests/testdata/localnet_with_resolution_local.toml
           python3 -m multiversx_sdk_cli.cli localnet start --configfile=./multiversx_sdk_cli/tests/testdata/localnet_with_resolution_local.toml --stop-after-seconds=120
 
-          grep -r --include=\*.log "started processing block - test" ./localnet || exit 1
+          if grep -r --include=\*.log "started processing block" ./localnet; then
+            echo "The localnet processed blocks successfully."
+          else
+            echo "The localnet failed to process blocks."
+            exit 1
+          fi
